### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by kvalov** [0x414c49/memrise-upload#1]
Windows Script Host
Line: 1
Char: 1
Error: Syntax error
Code: 800A03EA

PS E:\memrise-upload> node -v
v14.15.1
PS E:\memrise-upload> yarn --version
1.22.5

**Comment by 0x414c49** [comment]
You should not run the file directly in windows explorer. Inside command line (where you executed node -v) execute this command:

```
yarn run start
```

**Comment by kvalov** [comment]
I'm not sure what's going on:

PS E:\memrise-upload> yarn run start
yarn run v1.22.5
$ clear && jest --detectOpenHandles
'clear' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS E:\memrise-upload>

**Comment by 0x414c49** [comment]
I fixed that problem for you. Just download the source code again.

**Comment by kvalov** [comment]
Hi again. This is the output of the debugger.

Debugger attached.
 FAIL  ./index.spec.js (43.707s)
  Open memrise.com
    √ Navigate to login page (1366ms)
    √ Should fill username/password (81ms)
    √ Should log-in to Memrise (1311ms)
    √ Should find the course (9228ms)
    × Should insert all words (182ms)
    × Should upload all audio files (30023ms)

  ● Open memrise.com › Should insert all words

    Node is either not visible or not an HTMLElement

      101 |     let addBulkButton = await page.$("[data-role=level-bulk-add]");
      102 |     await page.focus("[data-role=level-bulk-add]");
    > 103 |     await addBulkButton.click();
          |     ^
      104 |     await page.waitFor(500);
      105 | 
      106 |     let data = words

      at ElementHandle._clickablePoint (node_modules/puppeteer/lib/JSHandle.js:216:13)
      at ElementHandle.click (node_modules/puppeteer/lib/JSHandle.js:282:20)
      at Object.<anonymous> (index.spec.js:103:5)
        -- ASYNC --
      at ElementHandle.click (node_modules/puppeteer/lib/helper.js:111:15)
      at Object.<anonymous> (index.spec.js:103:25)

  ● Open memrise.com › Should upload all audio files

    TimeoutError: waiting for selector "input.add_thing_file" failed: timeout 30000ms exceeded

      139 |     async () => {
      140 |       let audioCount = 0;
    > 141 |       await page.waitForSelector("input.add_thing_file");
          |                  ^
      142 |       let inputs = Array.from(await page.$$("input[type=file].add_thing_file"));
      143 |       for (let i = 0; i < words.length; i++) {
      144 |         let word = words[i];

      at new WaitTask (node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld._waitForSelectorOrXPath (node_modules/puppeteer/lib/DOMWorld.js:478:22)
      at DOMWorld.waitForSelector (node_modules/puppeteer/lib/DOMWorld.js:432:17)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:627:47)
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1122:29)
      at Object.<anonymous> (index.spec.js:141:18)
        -- ASYNC --
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:111:15)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1122:29)
      at Object.<anonymous> (index.spec.js:141:18)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 4 passed, 6 total
Snapshots:   0 total
Time:        43.913s
Ran all test suites.
Waiting for the debugger to disconnect...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Waiting for the debugger to disconnect...
PS E:\memrise-upload>
![1111](https://user-images.githubusercontent.com/20839717/101294272-eeb5d380-381e-11eb-8c9c-602547f3b523.JPG)

[
  {
    "German": "qwerty",
    "English": "asdfg",
    "audio": "0.mp3",
    "audioData": null
  },
  {
    "German": "qazwsx",
    "English": "edcrfv",
    "audio": "1.mp3",
    "audioData": null
  },
  {
    "German": "tgbyhn",
    "English": "ujmikl",
    "audio": "2.mp3",
    "audioData": null
  },
  {
    "German": "qscwdv",
    "English": "rtfgvb",
    "audio": "3.mp3",
    "audioData": null
  }
]
